<?xml version="1.0" encoding="utf-8"?><Database Name="UserCatalog" Class="UserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-F9KTQCL\SQLEXPRESS;Initial Catalog=UserCatalog;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="UserCatalogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserInfo" Member="UserInfos">
    <Type Name="UserInfo">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
</Database>